# Generated by Django 5.0 on 2023-12-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='body',
            field=models.TextField(default=' tell something', max_length=2000),
        ),
    ]
