# Generated by Django 5.0 on 2023-12-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_commodity_point_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='trade_time',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
