# Generated by Django 5.0 on 2023-12-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_session_trade_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='settlement',
            field=models.BooleanField(default=True),
        ),
    ]
