# Generated by Django 5.0 on 2023-12-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_strategy_settlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commodity_id',
            field=models.CharField(max_length=10, verbose_name='交易商品ID'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(max_length=10, verbose_name='交易商品名稱'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='point_value',
            field=models.PositiveIntegerField(default=200, verbose_name='一點的價格'),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=5, verbose_name='交易時段'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.CharField(max_length=10, verbose_name='交易時段ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='trade_time',
            field=models.CharField(default=' ', max_length=20, verbose_name='交易時間'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='body',
            field=models.TextField(default=' tell something', max_length=2000, verbose_name='策略描述'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='commodity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.commodity', verbose_name='交易商品'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='continue_loss',
            field=models.PositiveIntegerField(verbose_name='連續策略虧損次數'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='hazard_ratio',
            field=models.FloatField(verbose_name='風報比'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='mdd',
            field=models.IntegerField(verbose_name='最大策略回測'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(help_text='最多10字元', max_length=10, verbose_name='策略名稱'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='nums_trade',
            field=models.PositiveIntegerField(verbose_name='交易次數'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='profit',
            field=models.PositiveIntegerField(verbose_name='淨獲利'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='profit_factor',
            field=models.FloatField(verbose_name='獲利因子'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='填寫日期'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.session', verbose_name='交易時段'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='settlement',
            field=models.BooleanField(default=True, verbose_name='參加結算與否'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='strategy_id',
            field=models.CharField(max_length=10, verbose_name='策略ID'),
        ),
    ]
