# Generated by Django 5.0 on 2023-12-26 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_commodity_commodity_id_alter_commodity_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_id',
        ),
        migrations.CreateModel(
            name='PPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=20, verbose_name='簡單描述')),
                ('url', models.URLField(default='/')),
                ('name', models.CharField(default='', max_length=20)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.strategy', verbose_name='策略名稱')),
            ],
        ),
    ]
