# Generated by Django 5.0 on 2023-12-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_remove_session_session_id_pphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pphoto',
            name='description',
        ),
        migrations.AlterField(
            model_name='pphoto',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='圖片名稱'),
        ),
        migrations.AlterField(
            model_name='pphoto',
            name='url',
            field=models.URLField(default='/', max_length=500),
        ),
    ]
