# Generated by Django 5.0 on 2023-12-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_remove_pphoto_description_alter_pphoto_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pphoto',
            name='url',
            field=models.URLField(default='/', max_length=5000),
        ),
    ]
